[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "haltonseq"
version = "0.2.0"
description = "Simple Halton sequence generator"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "robert", email = "robert@valassi.se"}
]

[project.urls]
Homepage = "https://github.com/cogitoEdge/haltonseq"
