[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "matplotlib-matrix-legend"
version = "0.0.3"
authors = [
  { name="Igor Vaiman", email="gosha.vaiman@gmail.com" },
]
description = "Matrix legend layout for matplotlib"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/nj-vs-vh/matplotlib-matrix-legend"
Issues = "https://github.com/nj-vs-vh/matplotlib-matrix-legend/issues"

[tool.hatch.build.targets.sdist]
include = ["matrix_legend.py"]

[tool.hatch.build.targets.wheel]
include = ["matrix_legend.py"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"]  # check and fix imports
ignore = ["E202", "E251"]
