[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "greek_meander"
version = "0.0.1"
authors = [
  { name="bqiao", email="bqiaodev@gmail.com" },
]
description = "A package for generating Greek key meanders"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
keywords = ["greek key", "meander", "pattern", "generator", "svg"]

dependencies = [
    "drawsvg",
    "cairosvg",
]

[project.urls]
"Homepage" = "https://github.com/bingqiao/greek_meander"
"Bug Tracker" = "https://github.com/bingqiao/greek_meander/issues"

[project.scripts]
meander = "meander:main"
