[project]
name = "pyltover"
version = "0.1.8"
description = "Python wrapper around riot games developer api."
authors = [
    { name = "Sepehr Hamzehlouy", email = "s.hamzelooy@gmail.com" }
]
dependencies = [
    "pydantic>=2.11.7",
    "httpx>=0.28.1",
    "orjson>=3.10.18",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "ipdb>=0.13.13",
    "nest-asyncio>=1.6.0",
    "ruff>=0.12.9",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["pyltover"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
line-length = 120

[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
