[project]
name = "napalm-opengear-ng"
version = "0.1.0"
description = "NAPALM driver for Opengear CM81xx"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "napalm>=5.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
