[project]
name = "krishnautoml"
version = "1.0.1"
description = "Beginner-friendly AutoML library for tabular data"
authors = [
    { name = "Krishna", email = "krishnatyagi2526@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "jinja2",
    "joblib",
    "optuna",
    "optuna-integration[lightgbm]",
]

[project.optional-dependencies]
xgboost = ["xgboost"]
lightgbm = ["lightgbm"]
catboost = ["catboost"]

[project.scripts]
krishnautoml = "krishnautoml.cli:main"

[tool.setuptools.packages.find]
include = ["krishnautoml", "krishnautoml.*"]

[tool.setuptools.package-data]
"krishnautoml.reporting" = ["templates/*.html"]