[project]
name = "remote-web-typing"
version = "0.1.4"
description = "Remote Web Typing is a Python web application that lets you type on your computer from another device (like a phone) on the same network."
readme = "README.md"
authors = [
    { name = "mayank", email = "mayankchodharysept17@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "keyboard>=0.13.5",
    "pillow>=11.3.0",
    "pyautogui>=0.9.54",
    "pyperclip>=1.9.0",
]

[project.scripts]
remote-web-typing = "remote_web_typing.main:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[project.urls]
Homepage = "https://github.com/Mayank170906/remote-web-typing"
Issues = "https://github.com/Mayank170906/remote-web-typing/issues"
