[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name = "randompackage17"
version = "0.0.1"
authors = [
  { name="Aditya Velusamy", email="avelusamy@pm.me" },
]
description = "A mastermind package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Unlicense"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/avelusamy/randompackage"
Issues = "https://github.com/avelusamy/randompackage/issues"
