[project]
name = "cinetica"
version = "0.9.0"
description = "A Python library for physics modules."
authors = [
    { name = "Elabsurdo984", email = "matiassfernandez00@gmail.com" },
]
dependencies = [
    "numpy>=2.3.2",
    "matplotlib>=3.10.5"
]
requires-python = ">=3.13"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["physics", "library", "science"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.urls]
"Source Code" = "https://github.com/Elabsurdo984/Cinetica"
"Documentation" = "https://github.com/Elabsurdo984/Cinetica/blob/master/DOCS.md"
"Changelog" = "https://github.com/Elabsurdo984/Cinetica/blob/master/CHANGELOG.md"
"Bug Tracker" = "https://github.com/Elabsurdo984/Cinetica/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cinetica"]
