[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roboka"
version = "0.0.2"
description = "A Python wrapper for Rubika bot API"
authors = [{name = "Ali Zolghadr", email = "tradecoinex5@gmail.com"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "requests"
]