[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "ls-api-clients"
version = "0.30.0"
description = "A package for laser-mind clients"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "urllib3==1.26.13", "requests>=2.23", "msgpack>=1.0.0", "ls-cred-storage>=0.6.1", "PyJWT>=2.10.1", "laser-mind-client-meta>=0.0.9",]
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent",]
[[project.authors]]
name = "Assaf Kalinski"
email = "assaf@lightsolver.com"

[project.urls]
Homepage = "https://lightsolver.com"

[tool.setuptools.packages.find]
include = [ "ls_api_clients",]
