[project]
name = "orpheus-r"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "editdistance>=0.8.1",
    "ipykernel>=6.30.1",
    "mistral-common[audio]>=1.8.4",
    "openai>=1.105.0",
    "snac>=1.2.1",
    "verifiers[dev]>=0.1.3",
]
