[project]
name = "bytex"
version = "0.2.0"
description = "Pydantic-like binary validation"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest==8.3.5",
    "mypy==1.17.1",
    "black==25.1.0",
    "ruff==0.12.10"
]
examples = ["scapy==2.6.1"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
