[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cmdmate"
version = "0.1.6"
description = "cmdmate : Your AI powered terminal assistant ðŸš€"
readme = "README.md"
requires-python = ">=3.8,<3.14"
license = { text = "MIT" }
authors = [
  { name = "Chinmay Rao" }
]
dependencies = [
  "requests>=2.31,<3",
]

[project.urls]
Homepage = "https://github.com/mmchinmay555/cmdmate"
Repository = "https://github.com/mmchinmay555/cmdmate"

[project.scripts]
cmdmate = "client.cmdmate_cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["client", "client.*"]
exclude = ["server", "server.*", "tests", "tests.*"]

[tool.setuptools.exclude-package-data]
"*" = ["server/*", "tests/*", "*.pyc", "__pycache__"]