[project]
name = "philiarabbit"
version = "0.1.1"
description = ""
authors = [
    {name = "amir.ch.charehei1382@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pika (>=1.3.2,<2.0.0)",
    "aio-pika (>=9.5.7,<10.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "pytest-cov (>=6.2.1,<7.0.0)",
    "flask[async] (>=3.1.2,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
