[project]
name = "ryland"
version = "0.1.0"
description = "A simple static site generation library"
readme = "README.md"
license = "MIT"
authors = [
    { name = "James Tauber", email = "jtauber@jtauber.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "markdown>=3.8.2",
    "pyyaml>=6.0.2",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
