# SPDX-FileCopyrightText: Copyright (c) 2024 Aaron Silinskas for Mindwidgets
#
# SPDX-License-Identifier: MIT
[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[project]
name = "state-of-things"
description = "State of Things python library to organize complex state machines"
version = "0.0.2"
readme = "README.rst"
authors = [
    {name = "Mindwidgets", email = "aaron@mindwidgets.com"}
]
urls = {Homepage = "https://github.com/mindwidgets/state-of-things"}
keywords = [
    "circuitpython",
    "micropython",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {optional = {file = ["requirements-dev.txt"]}}
