[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "portal-env"
version = "0.8.1"
description = "A package that simplifies RL development by conveniently running RL environments in isolated Docker containers, avoiding dependencies conflicts. The agent interacts with the isolated environment through a Gymnasium interface that functions as a relay."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    {name = "Leor Cohen", email = "liorcohen5@campus.technion.ac.il"},
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "portal",
    "gymnasium",
    "click",
    "numpy",
    "pyyaml",
    "wget",
    "loguru",
]

[project.urls]
Homepage = "https://github.com/leor-c/portal-env"
Repository = "https://github.com/leor-c/portal-env.git"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
portal_env = ["envs/**/*.env"]

[project.scripts]
portal-env = "portal_env.env_side_cli:main"