[project]
name = "mcp-meteo"
version = "0.2.3"
description = "Serveur MCP pour accéder aux données météo via Open-Meteo"
readme = "README.md"
authors = [{ name = "Kerryan Mace", email = "kerryan.mace@student-cs.fr"}]
dependencies = ["fastmcp", "requests", "setuptools"]
requires-python = ">=3.10"


[project.scripts]
mcp-meteo = "mcp_meteo.server:main"

[project.urls]
Homepage = "https://github.com/KerryanOPMace/mcp-meteo"
Repository = "https://github.com/KerryanOPMace/mcp-meteo"
Issues = "https://github.com/KerryanOPMace/mcp-meteo/issues"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["."]
include = ["mcp_meteo*"]
exclude = ["client*", "test*", "env*", "dist*", "build*"]


[tool.setuptools.package-data]
mcp_meteo = ["*.py"]

[tool.uv]
dev-dependencies = []
