[project]
name = "milvus-dataset"
dynamic = []
description = "Default template for PDM package"
authors = [
    { name = "zhuwenxing", email = "wenxing.zhu@zilliz.com" },
]
dependencies = [
    "pydantic>=2.10.3",
    "pandas>=2.2.3",
    "fsspec>=2024.10.0",
    "pyarrow>=18.1.0",
    "s3fs>=2024.10.0",
    "gcsfs>=2024.10.0",
    "tqdm>=4.67.1",
    "loguru>=0.7.3",
    "scikit-learn>=1.6.0",
    "pymilvus>=2.5.0",
    "numba>=0.60.0",
    "datasets>=2.14.4",
    "colorama>=0.4.6",
    "ml-dtypes",
    "faker>=33.1.0",
    "modelscope>=1.21.0",
    "h5py>=3.12.1",
    "usearch>=2.12.0",
]
requires-python = ">=3.10"
readme = "README.md"
version = "1.0.0.post47"

[project.license]
text = "MIT"

[project.optional-dependencies]
gpu = [
    "cupy-cuda12x==13.3.0",
    "cuvs-cu12==24.12.0",
]
api = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "python-multipart>=0.0.20",
]
web = [
    "streamlit>=1.41.1",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[dependency-groups]
lint = [
    "ruff>=0.8.3",
]
test = [
    "pytest>=8.3.4",
    "pytest-cov>=4.1.0",
]
dev = [
    "mkdocs-material>=9.5.49",
    "mkdocstrings[python]>=0.27.0",
    "mkdocs-material-extensions>=1.3.1",
    "pdm-backend>=2.4.3",
    "keyring>=25.6.0",
    "keyrings-alt>=5.0.2",
    "mypy>=1.14.1",
    "pre-commit>=4.0.1",
]

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "C",
    "B",
    "UP",
    "N",
    "RUF",
]
ignore = [
    "E501",
]

[tool.ruff.lint.isort]
known-first-party = [
    "milvus_dataset",
]

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "scm"
version_format = "src.version:format_version"
write_to = "milvus_dataset/__version__.py"
write_template = "__version__ = '{}'\n"

[tool.pdm.scripts]
web = "streamlit run src/milvus_dataset/web/app.py"
api = "uvicorn src.milvus_dataset.api.main:app --reload --port 8000"
test = "pytest tests/  --cov-branch --cov=milvus_dataset --cov-report=xml --cov-report=html --cov-report=term-missing"
docs = "mkdocs serve"
docs-build = "mkdocs build"
