[project]
name = "email-to-calendar"
version = "20250907021936.dev"
description = "Takes emails from an IMAP server, parses the body, and creates event(s) in a CalDAV calendar"
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "caldav==2.0.1",
    "sqlalchemy==2.0.43",
    "tzlocal==5.3.1",
    "beautifulsoup4==4.13.5",
    "python-dateutil==2.9.0.post0",
    "html2text==2025.4.15",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
]
